# Generated by Django 5.2.4 on 2025-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='distance_km',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
