# Generated by Django 5.2.4 on 2025-08-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_destination_distance_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffhistory',
            old_name='tariff_per_km',
            new_name='tariff',
        ),
        migrations.RemoveField(
            model_name='tariffhistory',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trainevent',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trainevent',
            name='locomotive_number',
        ),
        migrations.AddField(
            model_name='trainevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wagon',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='distance_km',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
